#!/bin/sh
### BEGIN INIT INFO
# Provides:          connect3g
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop tightvncserver
### END INIT INFO
 
   echo "RUN CONNECT3G.PY!!!!!!!!!" 
   sudo nohup python /home/pi/connector/connect3g.py &
